Document: rllib
Title: Debian rllib Manual
Author: <insert document author here>
Abstract: This manual describes what rllib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rllib/rllib.sgml.gz

Format: postscript
Files: /usr/share/doc/rllib/rllib.ps.gz

Format: text
Files: /usr/share/doc/rllib/rllib.text.gz

Format: HTML
Index: /usr/share/doc/rllib/html/index.html
Files: /usr/share/doc/rllib/html/*.html
